name: Build qBittorrent v4_6_x Linux

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        sudo apt install autoconf autoconf-archive automake libtool libltdl-dev -y
        cd ~
        curl -s "https://archives.boost.io/release/1.86.0/source/boost_1_86_0.tar.gz" -o "boost_1_86_0.tar.gz"
        tar -xzf boost_1_86_0.tar.gz
        git clone --depth 1 https://github.com/microsoft/vcpkg.git
        cd vcpkg
        ./bootstrap-vcpkg.sh
        ./vcpkg install zlib:x64-linux openssl:x64-linux qt5-base:x64-linux qt5-svg:x64-linux qt5-tools:x64-linux --clean-after-build
    - name: Build libtorrent
      run: |
        git clone --recurse-submodules --branch RC_1_2 --depth 1 https://github.com/arvidn/libtorrent.git
        cd libtorrent
        cmake -G Ninja -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=\vcpkg\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-linux -DBUILD_SHARED_LIBS=OFF -Dstatic_runtime=ON -Ddeprecated-functions=OFF -DBoost_INCLUDE_DIR=\boost_1_86_0 -Wno-dev
        cmake --build build
        cmake --install build --prefix libtorrent-install

    - name: Build qBittorrent
      run: |
        git clone --branch v4_6_x --depth 1 https://github.com/qbittorrent/qBittorrent.git
        cd qBittorrent
        (Get-Content "src/base/CMakeLists.txt") -replace 'ZLIB::ZLIB', 'ZLIB::ZLIBSTATIC' | Set-Content "src/base/CMakeLists.txt"
        cmake -G Ninja -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows-static -DMSVC_RUNTIME_DYNAMIC=OFF -DLibtorrentRasterbar_DIR=C:\libtorrent-install\lib\cmake\LibtorrentRasterbar\ -DBoost_INCLUDE_DIR=C:\boost_1_86_0 -Wno-dev
        cmake --build build
        cmake --install build --prefix C:\qbt --strip

    - name: Upload artifact
      uses: actions/upload-artifact@v6
      with:
        name: qbt
        path: C:\qbt
